### ISSUE TITLE
LieRE for multiple modalities

### ISSUE THREAD

**Issue by logicwong** [SophieOstmeier/LieRE_implementation#1]
Thank you for this promising work! Recently, I have been attempting to unify all modalities within large language models (LLMs). LieRE seems to be a promising approach that has been underappreciated. I am curious about how LieRE handles positional vectors when the input includes text, video, and audio simultaneously. Could you provide some example code or further explanation on this? Thank you!

**Comment by p1nksnow** [comment]
I also notice your promising work! It seems that you sum the rotation matrices R of different input dimensions https://github.com/SophieOstmeier/LieRE_implementation/blob/eb64c5381a4956d221ebe3fddbc3a5f6256f9bc0/liere_rotations.py#L94
So it is essentially still one-dimensional position encoding?

**Comment by SophieOstmeier** [comment]
@logicwong Thank you for your question. 
Text, video, and audio have all different dimensions: Text 1D, video 3D, audio 1D. There are several option you could try.
1) Learning a basis matrix of shape (number of dimensions, head dimension, head dimension) for each of the modalities. 
2) Learning a basis matrix of (max number of dimensions, head dimension, head dimension) for all of the modalities, where the y and z dimensional positions for i.e. text are zero. In this way the matrices for the y and z dimensions in the case of lets say text are ignored. We have not tried this approach yet. The current LieRE paper focuses more on introducing the idea and testing it on 2D and 3D data. But there might be lots of variability with this approach. 

@p1nksnow Thank you for your comment.
It depends a bit how we define high dimensional. Since we do encode all possible dimensions (n-D) and produce a higher dimensional rotation matrix through matrix exponential (Lie groups), I maybe would error on the side of calling the position encoding higher dimensional compared to rope or rope 2D. 
To make this more clear, lets consider a 3D video, which has a x, y and z axis. We would learn a skew-symmetric basis matrix (3, head dimension, head dimension) and then sum over the dimensions (like you pointed out). This way all dimensions are encoded. If we then take the exponential of this basis matrix we get a high dimensional rotation matrix. In RoPE for example there is one degree of freedom for each phase. In LieRE, there are potentially more degrees of freedom if you think about it, thus more complex transformations might be learned.

**Comment by p1nksnow** [comment]
Thanks for your response, I am still confused about this, what difference would make if you have more degrees of freedom?  and how to really use LieRE in 2D,3D position...

> A skew-symmetric basis matrix (3, head dimension, head dimension) and then sum over the dimensions

it is still a skew-symmetric basis matrix after summation, right? And, LieRE use learnable parameters to represent skew-symmetric basis matrix, I think the learnable parameters(1, head dimension, head dimension) results equally to matrix with any dimension (x, head dimension, head dimension). Your code just converts higher position index into 1D position index and LieRE now only works on 1D dimension.

**Comment by SophieOstmeier** [comment]
the three above corresponds to the input dimension. It can be any input dimension though-the three is not critical. 

Each skew symmetric learned basis is multiplied by the position value of the corresponding coordinate. The sum of skew symmetric matrices is still a skew symmetric matrix. Thus we end up with a skew symmetric matrix per dimension of the input, then sum them to get a single skew symmetric matrix. That matrix is then exponentiated. 

May I advise running the code we published with, say 3D inputs, with a debugger? If you check the shapes at every step it should be much more visible how high dimensional inputs come into play.

As a side note the individual skew symmetric matrices per input dimension correspond to the basis in the Lie algebra sense, if you’re looking for a bit more intuition for why this makes sense to do and how it preserved the high dimensional structure.

Hope this was helpful!

**Comment by p1nksnow** [comment]
Thank you for your response
